### ISSUE TITLE
using other alternative relays

### ISSUE THREAD

**Issue by nbourbon** [vilm3r/sendstr-web#1] opened 2022-12-17 02:27 UTC
Hi, I tried using other relays just to see how it works but when using other relays it doesn't. it seems it's only with your default relay that works?.. is this using a specific thing that other relays don't understand?

**Comment by vilm3r** [comment] 2022-12-17 04:26
Senstr only uses kind 4 events currently so it should work with all relay implementations. What relay did you try? I tested with wss://nostr-pub.wellorder.net and it's working for me.

**Comment by nbourbon** [comment] 2022-12-17 19:01
somehow now it's not working with any of the relays to me. I tried the one you mentioned and the default one. maybe it's because it's all exploding now with so much demand?

**Comment by vilm3r** [comment] 2022-12-17 20:00
I'm not able to reproduce the issue with the provided details so closing this issue. I set up an issue template for bugs so you can open another issue with device/browser/relay details and screenshots if you want.

**Closed by vilm3r** 2022-12-17 20:00 UTC
